version:     "0003--21-Sep-2022"
copyright:   "2022"
author:      "Johannes Setiawan"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/JohannesSetiawan/os222/"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
